### ISSUE TITLE
I met some trouble on "configs/default.py"!

### ISSUE THREAD

**Issue by hzwfl2** [LouieYang/AttentionZSL#1]
Hi, as you described, I downloaded the CUB dataset into  "data/CUB/JPEGImages" and tried to run "python experiments/run_trainer.py --cfg ./configs/self_adaptation/VGG19_CUB_PS_C.yaml". However, I got "configs\default.py", line 72,  SyntaxError: invalid syntax". Can you help me to fix it? Thanks!

**Comment by LouieYang** [comment]
f"{}" syntax is favored by python>=3.6
