### ISSUE TITLE
About the network arch you use for SUN and CUB dataset

### ISSUE THREAD

**Issue by Albert0147** [LouieYang/AttentionZSL#2]
About the results in the paper, I guess the networks you deploy for CUB and SUN (inductive setting) are not the VGG 19, but the GoogleNet or ResNet?

**Comment by LouieYang** [comment]
The arch of inductive reported performances in the paper are: CUB SS(GoogleNet), CUB PS(ResNet101), SUN SS(ResNet101), SUN PS(ResNet101)
