### ISSUE TITLE
How to get the " predicate-matrix-continuous.txt" of cub awa dataset?

### ISSUE THREAD

**Issue by zwy1996** [LouieYang/AttentionZSL#3]
Hi,

Thanks for your excellent work!
I have met the problem that how you get the " predicate-matrix-continuous.txt" of cub awa dataset,
if I want use imagenet dataset to train a model，could I get the file of imagenet?

Thank you again!

**Comment by LouieYang** [comment]
"predicate-matrix-continuous.txt" is originally included in AwA and CUB datasets. The AwA website gives the way they do this annotation.   

I think the imagenet dataset doesn't have this annotation which would take you much time if you want to label them by yourself.

**Comment by zwy1996** [comment]
Thanks，I get it.

**Comment by zwy1996** [comment]
Hello, Thanks for your help, I am sorry to bother you again,
When I read the paper that AWA website, I could not  undertstand the insight,
Could you help me offer another material？
Thank you very much!
