### ISSUE TITLE
The AWA2 dataset

### ISSUE THREAD

**Issue by zwy1996** [LouieYang/AttentionZSL#4]
Hello, Thanks for your excellent work!

You know the awa2 dataset that download from official website was so slowly, could you help me with 
a baiduyunpan link?

Thank you very much!

**Comment by LouieYang** [comment]
The uploading also takes time for 10G image files. Maybe you can try some VPN service by your own.

**Comment by zwy1996** [comment]
Thank you.
When I saw the download result, I found I have finished the AWA2 dataset from official website.
Maybe the speed was faster in the evening!
