### ISSUE TITLE
The poor perfermance of awa2 ps g ?

### ISSUE THREAD

**Issue by zwy1996** [LouieYang/AttentionZSL#5]
Hello, When I used "python experiments/run_trainer.py --cfg ./configs/self_adaptation/VGG19_AwA2_PS_G.yaml" and "python experiments/run_evaluator.py --cfg ./configs/self_adaptation/VGG19_AwA2_PS_G.yaml" to train and test on awa2 dataset, I got 0 accuracy?
Do you know why met the  problem?

ckpt_epoch_15.pth
	 tr: 0.02500, ts: 0.00000, H: 0.00000

**Comment by LouieYang** [comment]
Have you checked if you load "attribute" file, image file and checkpoint file successfully? Is the accuracy normal for the provided checkpoint?

**Comment by zwy1996** [comment]
Thank you！Could you offer with the VGG19_CUB_PS model and VGG19_AwA2_SS model. Could I use  your VGG19_AwA2_PS model  on "c" and "g" setings ?

**Comment by zwy1996** [comment]
Hello, I used your vgg19 model, but I also got the a little poor performance, CUB ss c : 78.567 vs 80.0 in your paper. AWA2 PS c: 75.895 vs 75.5 , AWA2 PS g:  tr:0.02500      ts:0.00000      H:0.00000, it was a little strange. Could you help me with this problem? I only used your code and didn't fix.

**Comment by LouieYang** [comment]
Seems like problems occur for "PS G" evaluation when I merge and clean codes. Problems only happen in function "labeling"  in "self_adaptation.py" with phase "metric=euclidean, ensemble=False". I will fix it asap when servers in school restart.

**Comment by zwy1996** [comment]
OK，Thanks a lot.

**Comment by GA-17a** [comment]
@LouieYang Hi, the problem on the "PS G" setting still exists.

**Comment by GA-17a** [comment]
@zwy1996 Hi, do you solve the probelm on "PS G" setting?
