### ISSUE TITLE
The meaning of data of predicate-matrix-continuous.txt

### ISSUE THREAD

**Issue by zwy1996** [LouieYang/AttentionZSL#6]
Hi,

I am sorry to bother you about the meaning of data of predicate-matrix-continuous.txt.

How do you understand the "  The number is the percentage of the time (between 0 and 100) that a human thinks that the attribute is present for a given class" which in the readme.txt of CUB dataset.

But In the  awa dataset, data of predicate-matrix-continuous.txt had negative number，could you help me with the correct understanding of this?

Thank you very much!

**Comment by LouieYang** [comment]
I think the negative "-1" in AwA is missing data or so-called "dirty data" and is cleaned by almost all ZSL methods (replacing -1 with 0).
